In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
df = pd.read_csv("retail_store_sales.csv")

df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False

In [3]:
print("Dataset Shape:", df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

Dataset Shape: (12575, 11)

Column Names:
['Transaction ID', 'Customer ID', 'Category', 'Item', 'Price Per Unit', 'Quantity', 'Total Spent', 'Payment Method', 'Location', 'Transaction Date', 'Discount Applied']

Data Types:
Transaction ID          str
Customer ID             str
Category                str
Item                    str
Price Per Unit      float64
Quantity            float64
Total Spent         float64
Payment Method          str
Location                str
Transaction Date        str
Discount Applied     object
dtype: object

Missing Values:
Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

Duplicate Rows:
0

In [4]:
df.describe(include='all')

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
count,12575,12575,12575,11362,11966.000000,11971.000000,11971.000000,12575,12575,12575,8376
unique,12575,25,8,200,NaN,NaN,NaN,3,2,1114,2
top,TXN_6867343,CUST_05,Furniture,Item_2_BEV,NaN,NaN,NaN,Cash,Online,2022-05-30,True
freq,1,544,1591,126,NaN,NaN,NaN,4310,6354,26,4219
mean,NaN,NaN,NaN,NaN,23.365912,5.536380,129.652577,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,10.743519,2.857883,94.750697,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,5.000000,1.000000,5.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,14.000000,3.000000,51.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,23.000000,6.000000,108.500000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,33.500000,8.000000,192.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,41.000000,10.000000,410.000000,NaN,NaN,NaN,NaN

In [5]:
missing = df.isnull().sum()

missing_percent = (df.isnull().sum() / len(df) * 100).round(2)

quality_missing = pd.DataFrame({
    'Missing Count': missing,
    'Missing %': missing_percent
})

quality_missing

                  Missing Count  Missing %
Transaction ID                0       0.00
Customer ID                   0       0.00
Category                      0       0.00
Item                       1213       9.65
Price Per Unit              609       4.84
Quantity                    604       4.80
Total Spent                 604       4.80
Payment Method                0       0.00
Location                      0       0.00
Transaction Date              0       0.00
Discount Applied           4199      33.39

In [6]:
duplicate_count = df.duplicated().sum()

print("Duplicate rows before cleaning:", duplicate_count)

Duplicate rows before cleaning: 0

In [7]:
df = df.drop_duplicates().copy()

print("Duplicate rows after cleaning:", df.duplicated().sum())

Duplicate rows after cleaning: 0

In [9]:
text_columns = df.select_dtypes(include=['object', 'string']).columns

print("Text columns:")
print(text_columns.tolist())

Text columns:
['Transaction ID', 'Customer ID', 'Category', 'Item', 'Payment Method', 'Location', 'Transaction Date', 'Discount Applied']

In [10]:
for col in text_columns:
    df[col] = df[col].astype('string').str.strip()

print("Text formatting standardized.")

Text formatting standardized.

In [11]:
print(df.dtypes)

Transaction ID       string
Customer ID          string
Category             string
Item                 string
Price Per Unit      float64
Quantity            float64
Total Spent         float64
Payment Method       string
Location             string
Transaction Date     string
Discount Applied     string
dtype: object

In [12]:
if 'Date' in df.columns:
    df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

print(df.dtypes)

Transaction ID       string
Customer ID          string
Category             string
Item                 string
Price Per Unit      float64
Quantity            float64
Total Spent         float64
Payment Method       string
Location             string
Transaction Date     string
Discount Applied     string
dtype: object

In [13]:
print("Before:")
print(df.dtypes)

if 'Transaction Date' in df.columns:
    df['Transaction Date'] = pd.to_datetime(
        df['Transaction Date'], errors='coerce'
    )

print("\nAfter:")
print(df.dtypes)

Before:
Transaction ID       string
Customer ID          string
Category             string
Item                 string
Price Per Unit      float64
Quantity            float64
Total Spent         float64
Payment Method       string
Location             string
Transaction Date     string
Discount Applied     string
dtype: object

After:
Transaction ID              string
Customer ID                 string
Category                    string
Item                        string
Price Per Unit             float64
Quantity                   float64
Total Spent                float64
Payment Method              string
Location                    string
Transaction Date    datetime64[us]
Discount Applied            string
dtype: object

In [14]:
numeric_columns = df.select_dtypes(include=np.number).columns

print("Numeric columns:")
print(numeric_columns.tolist())

Numeric columns:
['Price Per Unit', 'Quantity', 'Total Spent']

In [15]:
for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')

print(df.dtypes)

Transaction ID              string
Customer ID                 string
Category                    string
Item                        string
Price Per Unit             float64
Quantity                   float64
Total Spent                float64
Payment Method              string
Location                    string
Transaction Date    datetime64[us]
Discount Applied            string
dtype: object

In [16]:
print(df.columns.tolist())
print("\nMissing values:")
print(df.isnull().sum())
print("\nData types:")
print(df.dtypes)

['Transaction ID', 'Customer ID', 'Category', 'Item', 'Price Per Unit', 'Quantity', 'Total Spent', 'Payment Method', 'Location', 'Transaction Date', 'Discount Applied']

Missing values:
Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

Data types:
Transaction ID              string
Customer ID                 string
Category                    string
Item                        string
Price Per Unit             float64
Quantity                   float64
Total Spent                float64
Payment Method              string
Location                    string
Transaction Date    datetime64[us]
Discount Applied            string
dtype: object

In [17]:
missing = df.isnull().sum()
missing = missing[missing > 0]

print("Missing values:")
print(missing)

Missing values:
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Discount Applied    4199
dtype: int64

In [18]:
missing_report = pd.DataFrame({
    'Missing Count': df.isnull().sum(),
    'Missing %': (df.isnull().sum() / len(df) * 100).round(2)
})

missing_report = missing_report[missing_report['Missing Count'] > 0]

missing_report

                  Missing Count  Missing %
Item                       1213       9.65
Price Per Unit              609       4.84
Quantity                    604       4.80
Total Spent                 604       4.80
Discount Applied           4199      33.39

In [19]:
print(df.columns.tolist())
print("\nMissing values:")
print(df.isnull().sum())

['Transaction ID', 'Customer ID', 'Category', 'Item', 'Price Per Unit', 'Quantity', 'Total Spent', 'Payment Method', 'Location', 'Transaction Date', 'Discount Applied']

Missing values:
Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [20]:
# Numeric columns → median
numeric_cols = df.select_dtypes(include=np.number).columns

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

# Text columns → mode
text_cols = df.select_dtypes(include=['object', 'string']).columns

for col in text_cols:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].mode()[0])

print("Missing values after cleaning:")
print(df.isnull().sum())

Missing values after cleaning:
Transaction ID      0
Customer ID         0
Category            0
Item                0
Price Per Unit      0
Quantity            0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
Discount Applied    0
dtype: int64

In [21]:
total_missing = df.isnull().sum().sum()

print("Total missing values:", total_missing)

Total missing values: 0

In [22]:
outlier_report = {}

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outlier_count = ((df[col] < lower) | (df[col] > upper)).sum()
    outlier_report[col] = outlier_count

outlier_report

{'Price Per Unit': np.int64(0),
 'Quantity': np.int64(0),
 'Total Spent': np.int64(157)}

In [23]:
outlier_report

{'Price Per Unit': np.int64(0),
 'Quantity': np.int64(0),
 'Total Spent': np.int64(157)}

In [24]:
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df[col] = df[col].clip(lower=lower, upper=upper)

print("Outliers capped using IQR method.")

Outliers capped using IQR method.

In [25]:
outlier_after = {}

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outlier_after[col] = ((df[col] < lower) | (df[col] > upper)).sum()

print(outlier_after)

{'Price Per Unit': np.int64(0), 'Quantity': np.int64(0), 'Total Spent': np.int64(0)}

In [26]:
print("Duplicate rows:", df.duplicated().sum())
print("Total rows:", len(df))
print("Total missing values:", df.isnull().sum().sum())

Duplicate rows: 0
Total rows: 12575
Total missing values: 0

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  string
 1   Customer ID       12575 non-null  string
 2   Category          12575 non-null  string
 3   Item              12575 non-null  string
 4   Price Per Unit    12575 non-null  float64
 5   Quantity          12575 non-null  float64
 6   Total Spent       12575 non-null  float64
 7   Payment Method    12575 non-null  string
 8   Location          12575 non-null  string
 9   Transaction Date  12575 non-null  datetime64[us]
 10  Discount Applied  12575 non-null  string
dtypes: datetime64[us](1), float64(3), string(7)
memory usage: 1.1 MB

In [28]:
before_df = pd.read_csv("retail_store_sales.csv")

summary = pd.DataFrame({
    "Metric": [
        "Total Rows",
        "Total Columns",
        "Missing Values",
        "Duplicate Rows"
    ],
    "Before Cleaning": [
        len(before_df),
        len(before_df.columns),
        before_df.isnull().sum().sum(),
        before_df.duplicated().sum()
    ],
    "After Cleaning": [
        len(df),
        len(df.columns),
        df.isnull().sum().sum(),
        df.duplicated().sum()
    ]
})

summary

           Metric  Before Cleaning  After Cleaning
0      Total Rows            12575           12575
1   Total Columns               11              11
2  Missing Values             7229               0
3  Duplicate Rows                0               0

In [29]:
df.to_csv("retail_store_sales_cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [30]:
cleaned_df = pd.read_csv("retail_store_sales_cleaned.csv")

print("Cleaned dataset shape:", cleaned_df.shape)
print("\nMissing values:")
print(cleaned_df.isnull().sum().sum())
print("\nDuplicate rows:")
print(cleaned_df.duplicated().sum())

Cleaned dataset shape: (12575, 11)

Missing values:
0

Duplicate rows:
0

## Conclusion

The dataset was cleaned and transformed into an analysis-ready format.

The cleaning process included:
- Missing value analysis and treatment
- Duplicate row detection and removal
- Text formatting standardization
- Date format correction
- Numeric data type correction
- Outlier detection using the IQR method
- Outlier capping
- Before vs After data quality comparison

The cleaned dataset was saved as `retail_store_sales_cleaned.csv`.